project:
  type: website

website:
  title: "Statistics Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/p-lahanas
format:
  html:
    theme:
      - lux
      - brand
    css: styles.css
